title:              CCPA 회장 이다.
email:              dwkang0@gmail.com
description:        CCPA의 공식 블로그 이다. 소식 도 전한 다.
author:             Start Bootstrap
baseurl:            ""
url:                "https://ccpablog.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    dwkang0
facebook_username:  StartBootstrap
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
