title:              CCPA
email:              dwkang0@gmail.com
description:        ((((･ิ(･ิω(･ิω･ิ)ω･ิ)･ิ))))
author:             CCPA
baseurl:            ""
url:                "https://ccpablog.github.io"

disqus_url: disqus.com/by/ccpablog
disqus_id: ccpablog

# Social Profiles
twitter_username:
github_username:    dwkang0
facebook_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
